#!/usr/bin/env python
# coding: utf-8

# In[1]:


# This file contains errors in the NER locations results that Laura manually filtered out


# Jacob's room the list contains the correct locations

# comparing this list to the visualised NE and studying the context requires us to revise the list
# and exclude all misclassified items 
# we manually sieve through the list and store the revised edition in a variable

# for Voyage out and Night and Day another approach was used.
# They contain the misclassified ones

#the variables are: jacob_correct_locations, nightday_misclassified, voyageout_misclassified

jacob_correct_locations = ['Scarborough',
'Cornwall',
'Scarborough',
'Dods Hill', 
'Scarborough',
'Dods Hill', 
'Scarborough',
'Sheffield',
'Sheffield',
'Scarborough',
'Cambridge',
'Cambridge',
'Cambridge',
'Cambridge',
'Cambridge', 
'Cambridge',
'Persia',
"Neville's Court",
"Neville's Court",
'Cambridge',
'London',
'Cambridge', 
'Turkey', 
'Cambridge', 
'Indian Ocean', 
'Cambridge', 
'Italy', 
'Greece', 
'Spain', 
'Cornwall',
'America',
'Atlantic', 
'London', 
'Holborn', 
"St. Paul's", 
"St. Paul's", 
"St. Paul's", 
'Acton', 
'Holloway',
'Leeds', 
'Cambridge', 
'London', 
'London', 
'London', 
'London', 
"St. Paul's", 
'London', 
'Greece', 
'Gibraltar',
'London', 
'London', 
'Athens', 
'US',
'London', 
'Notting Hill', 
'Farquhars', 
'Banchorie',
'London', 
'America', 
'New York',
'Ireland', 
'India',
'Scarborough', 
'London', 
'Holborn', 
'Albany', 
'London', 
'London', 
'London', 
"St. Paul's", 
'England', 
'Ireland', 
'Ireland', 
'Walworth', 
'London', 
'New Square',
'Yorkshire', 
'Britannia', 
'Hyde Park', 
'Rome', 
'Greece', 
'China', 
'India', 
'Persia',
'Paris',
'Strand',
'Strand', 
'St. Pancras', 
'Holborn', 
'Holborn',
'Ireland', 
'Paris', 
'Paris', 
'Greece', 
'London', 
'Greece', 
'Paris', 
'Scarborough',
'England',
'Devonshire',
'Italy', 
'Paris', 
'Paris',
'Italy', 
'Italy', 
'Greece', 
'Rome', 
'Athens', 
'Italy', 
'Greece', 
'Greece', 
'France', 
'Italy', 
'India', 
'Rome', 
'Greece', 
'Greece', 
'Ireland', 
'Milan',
'England', 
'Greece', 
'England', 
'England', 
'America', 
'Greece',
'Greece', 
'Athens', 
'Athens', 
'Greece', 
'Athens', 
'Mount Hymettus', 
'Athens', 
'Athens', 
'Athens', 
'Mycenae',
'the North Sea', 
'Germany', 
'Williamses', 
'England', 
'London', 
'Athens', 
'Greece', 
'the Sea of Marmara', 
'Greece', 
'Greece', 
'Albania', 
'Turkey', 
'Paris', 
'London', 
'England', 
'Athens', 
"St. Peter's", 
"St. Paul's", 
'London', 
'Surbiton', 
'Fetter Lane', 
'Bedford', 
'Fetter Lane', 
'Hyde Park', 
'Hyde Park', 
'Greece', 
'Greece', 
'Albany', 
'England', 
'London', 
'Morocco', 
'Venezuela', 
'Regent Street', 
'Hyde Park',
'Rome', 
'Hyde Park', 
'Milan', 
'Vienna', 
'Gibraltar', 
'Albania', 
'Hyde Park', 
'Piccadilly', 
'Long Acre', 
'Putney', 
'Long Acre', 
'Greece', 
'Cornwall', 
'Scarborough', 
'Scarborough',
'Dods Hill', 
'Dods nHill', 
'Crimea',
'Maresfield House',
'Dods Hill', 
'Broad Street', 
'Scarborough', 
'Oxford', 
'Mudie', 
"King's College Chapel", 
"King's College Chapel",
'Falmouth',
"the Land's End", 
'Southampton Row', 
'Mudie', 
'Oxford Street',
'Ludgate Hill', 
'the Union of London', 
"Smith's Bank", 
'Bank', 
'the Opera House', 
'the Opera House',
'Parliament Hill',
'Haverstock Hill',
'Haverstock Hill',
'the British Museum', 
'Tube', 
'Clerkenwell', 
"Gray's Inn", 
'Bond Street',
'Scarborough',
'Greek Street',
'Shaftesbury Avenue',
'Grosvenor Square',
'Endell Street', 
'Covent Garden', 
'Lincoln',
'The North of England',
'the British Museum', 
'the British Museum', 
'the British Museum', 
'the British Museum', 
'the British Museum',
'the British Museum', 
'The British Museum', 
'Kentish Town', 
'Highgate', 
'the British Museum',
'Piccadilly', 
'Bridge', 
'Putney', 
'Strand', 
'Bridge', 
'Somerset House', 
'Temple Bar',
'Leicester Square', 
'Hampstead Garden Suburb', 
'the Foundling Hospital',
'Shaftesbury Avenue',
'Temple', 
'Gerrard Street', 
'Gerrard Street', 
'Charing Cross Road',
'Lowndes Square',
'Dods Hill'
'the Boulevard Raspaille', 
'the British Museum', 
'the Gare des Invalides',
'Scarborough', 
'Parthenon', 
'Coliseum', 
'Patras', 
'the Foundling Hospital',
'Marathon',
'Parthenon', 
'Parthenon', 
'the Temple of Victory', 
'Parthenon', 
'Parthenon', 
'Parthenon', 
'Parthenon', 
'Marathon',
'Marathon', 
'Parthenon', 
'Parthenon', 
'Erechtheum', 
'Sloane Street', 
'Serpentine', 
'the Square of the Constitution',
'Hermes Street', 
'the Square of the Constitution',
'Parthenon',
'Delphi',
'Eastern',
'Lombard Street', 
'Bedford Square', 
'The Bank of England', 
'London Bridge', 
'Serpentine',
'Parthenon',
'Cursitor Street', 
'Bruton Street', 
'Parthenon', 
'Parthenon',  
'the British Museum', 
'Charing Cross',
'Calcutta', 
'Kensington Palace', 
'Serpentine', 
'Opera House', 
'Parthenon', 
'Mudie']

# a list of misclassified items in Night and Day

nightday_misclassified = ["Katharine", 
"Katharine’s", 
"the Battle of Trafalgar",
"Armada",
"Denham",
"Denham’s",
"the Relief of Lucknow",
"Hilberys",
"d’you",
"Darnley’s",
"Sudden",
"Underground",
"Bobbie",
"the\nMillingtons",
"State",
"Havelock",
"The\nAlardyces",
"Church",
"Elizabethan",
"Emerson",
"Duchess",
"Rodney’s",
"Latin",
"Latin\n",
"William’s",
"Cockney",
"Clacton",
"S.R.F.R.",
"Central",
"Salford’s",
"Patridge's",
"House",
"Hugo\nand Alfred de Musset",
"Cabinet\n",
"Dante",
"That’s",
"Mamma",
"Bungay",
"Cyril\n",
"Byron",
"Keats’s",
"Aunt Celia",
"Alfred",
"Cyril",
"Cyril’s",
"Melbury House",
"Empress",
"Queenie Colquhoun",
"the\nBoard of Trade",
"Alardyce",
"Cromwell",
"East",
"the House of Commons",
"a Liberal Government",
"Heraldry",
"the\nWomen’s Suffrage Bill",
"Ralph’s",
"Sylvano",
"Gratian’s",
"the England of the Elizabethan age",
"Romney",
"Belloc",
"Honor",
"Beatrice",
"Antigone",
"Lewes",
"Millais",
"Maggie’s",
"seem”—she",
"Cabinet",
"Bazaar",
"the Imperial Hotel",
"the Queen's Hall",
"the Grafton Gallery",
"Mary",
"Elgin",
"Constrained",
"Trantem Abbey",
"the\nChurch",
"Elizabeth’s",
"Otway",
"Stogdon House",
"Humphrey",
"Marmaduke",
"Middletons",
"’s",
"Stanham",
"Bolham Hall",
"Charlotte",
"the\nLife of Richard Alardyce",
"Hilda’s",
"Lady Otway’s",
"the Indian Army",
"Vicarage",
"the\nGovernment Offices",
"Katharine Hilbery",
"Providence",
"’ve",
"Mary?—we",
"the Suffrage Office",
"Ministers",
"Parliament",
"Society",
"the\nGovernment",
"Cabinet Ministers",
"Bar",
"Peevishness",
"we’ve",
"Shelley’s",
"Chippendale",
"Mary",
"Dearest William",
"Cassandra’s",
"the Indian Empire",
"Hamlet",
"Trevor",
"Ophelia",
"Wagner",
"Secretaryship",
"Mary’s",
"Queer",
"the\nHilberys",
"Circumstances",
"Tube",
"Middletons",
"Johnnie",
"Hester",
"the Aalvation Army",
"Johnnie's",
"Judson",
"Parliament",
"Sabbath",
"Violet",
"Aunt\n",
"Aunt Celia",
"Mozart",
"Byron",
"Shakespeare’s",
"Bradshaws",
"Grateley's",
"Coliseum",
"Camberwell",
"the Welsh\nHarp",
"Polar",
"the Mile End\nRoad",
"Cyril",
"Registry Office",
"Abbey",
"the Church of England",
"the Board of Education",
"Time",
"Sally Seal’s",
"Museum",
"Hilbery",
"Aunt Celia’s",
"Partridge’s",
"Cousin",
"King’s",
"Henry’s",
"Henry",
"Katharine\n",
"Katherine",
"Grateley’s",
"Bingham",
"the Salvation Army",
"Terrace",
"Press",
"the\nPress"] 

# misclassified items in Voyage Out

voyageout_misclassified = ["the Great House of Tarquin",
"the London County Council\nfor Night Schools",
"Helen",
"Perhaps--",
"the\nAmazons",
"Odysseus",
"Aunt Bessie",
"Rachel\n",
"Ridley",
"Willoughby",
"Santa Marina Helen",
"Theresa",
"Aristotle",
"the University Press",
"Chailey",
"Cowper",
"Aunt Lucy",
"reasons'--and",
"Hunts",
"Parliament",
"Glenaway",
"East",
"Fielding",
"Amazons",
"Tagus",
"Olney",
"Pepper",
"Reynolds",
"Isolde",
"Wagner",
"Watts",
"Vinrace",
"North",
"House",
"Clarice",
"Emerson",
"Heights",
"Cowper's",
"it!--_every_thing",
"Trinity",
"Park",
"Zoo",
"Atlantic",
"Champagne",
"Speech",
"Rebellion",
"Wuthering Heights",
"Moffatt", 
"R.E.",
"United\nService",
"Cockney", 
"Elizabethan",
"the British Empire", 
"Santa Marina", 
"Helen Ambrose's",
"the Villa San Gervasio\n",
"British Consul",
"General Election\n",
"Mall", 
"Wordsworth",
"Lounge",
"the\nManns",
"Appleby",
"Hewet",
"Hughling the Oxford Don",
"Aunt Emma", 
"Times",
"Hannibal", 
"Eeles Park", 
"Brondesbury",
"Coptic",
"Company", 
"Hilda",
"Hirst",
"Meredith",
"St. John",
"Santa\nMarina",
"Hughling\n",
"Bar",
"allowed--",
"St. John Alaric Hirst",
"Great Wappyng",
"Rachel",
"Wagner and Beethoven",
"Warrington",
"Dorsershire",
"Jorrocks",
"Addison",
"Speech",
"St. J. A. H.",
"Aethiopia",
"Tottie Hall Green",
"Torquay",
"Lakes",
"Huths",
"The\nPatience",
"Truefit",
"Pinwells",
"Archbishop",
"Hugh",
"Ambroses",
"Friendship",
"England--Chillingley",
"Ridley's",
"Mouldy",
"the Nethermost Pit",
"the\nEnglish",
"the\n",
"much'--she",
"himself--'St", 
"John Stuart Mill",
"Watts",
"Blanche",
"G.F.S.",
"St. John Hirst",
"Thackeray",
"Serpentine",
"the\nElliots", 
"Thornburys", 
"Flushings",
"Pindar",
"Terence",
"the Old Testament", 
"the New Testament",
"Litany",
"Egyptology",
"Drat",
"the National Anthem",
"Crooms", 
"the Liberal\nparty",
"Sinclair", 
"Evelyn",
"the Deptford Road",
"the Saturday Club",
'prostitution"--she',
"Terence\n",
"Wilfrid",
"Alice",
"Greeley",
"South\n",
"Valley",
"Hugh\n",
"Strand",
"Thornbury",
"Pepper",
"Locrine",
"Brute",
"Rodriguez",
"Chailey\n",
"Penge",
"Hughling Elliot",
"Mars",
"St. John's",
"Eliotts",
'much"--she',
"Rachel's",
"Alfred",
"Johnsons",
"Neville", 
"Betty",
'reasons"--and',
"Aunt Clara",
"Clarissa",
"Elliots",
"Stepping",
"Mackenzie"]


# In[ ]:




